QT += core sql qml quick quick widgets positioning serialport

CONFIG += c++11

SOURCES += main.cpp \
    database/linesModel.cpp \
    database/database.cpp \
    models/rulerModel.cpp \
    database/tracksmodel.cpp \
    database/pointsphotomodel.cpp \
    database/pointsmodel.cpp \
    database/locationsmodel.cpp \
    database/imagesmodel.cpp \
    exif/exifinfo.cpp \
    backend/tilesdownloader.cpp \
    providers/photoprovider.cpp \
    math/variation_method_calibrate.cpp \
    math/calibrate_known_info.cpp \
    database/changedb.cpp \
    providers/iconsprovider.cpp \
    providers/qcvhelper.cpp \
    backend/photototiles.cpp \
    models/currentphotopointer.cpp \
    serial_link.cpp \
    abstract_link.cpp \
    gcs_communicator_factory.cpp \
    abstract_communicator_factory.cpp \
    mavlink_communicator.cpp \
    hearthbeat_handler.cpp \
    abstract_handler.cpp \
    attitude_handler.cpp \
    models/missionmodel.cpp

RESOURCES += qml.qrc

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

win32:RC_ICONS += icon.ico

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

HEADERS += \
    database/linesModel.h \
    database/database.h \
    providers/sliderimageprovider.h \
    models/rulerModel.h \
    database/tracksmodel.h \
    database/pointsphotomodel.h \
    database/pointsmodel.h \
    database/locationsmodel.h \
    database/imagesmodel.h \
    providers/iconsprovider.h \
    exif/exifinfo.h \
    backend/tilesdownloader.h \
    providers/photoprovider.h \
    math/variation_method_calibrate.h \
    math/calibrate_known_info.h \
    database/changedb.h \
    providers/qcvhelper.h \
    backend/photototiles.h \
    models/currentphotopointer.h \
    mavlink/ardupilot/ardupilotmega.h \
    mavlink/ardupilot/mavlink.h \
    mavlink/ardupilot/mavlink_msg_ahrs.h \
    mavlink/ardupilot/mavlink_msg_ahrs2.h \
    mavlink/ardupilot/mavlink_msg_ahrs3.h \
    mavlink/ardupilot/mavlink_msg_airspeed_autocal.h \
    mavlink/ardupilot/mavlink_msg_ap_adc.h \
    mavlink/ardupilot/mavlink_msg_autopilot_version_request.h \
    mavlink/ardupilot/mavlink_msg_battery2.h \
    mavlink/ardupilot/mavlink_msg_camera_feedback.h \
    mavlink/ardupilot/mavlink_msg_camera_status.h \
    mavlink/ardupilot/mavlink_msg_compassmot_status.h \
    mavlink/ardupilot/mavlink_msg_data16.h \
    mavlink/ardupilot/mavlink_msg_data32.h \
    mavlink/ardupilot/mavlink_msg_data64.h \
    mavlink/ardupilot/mavlink_msg_data96.h \
    mavlink/ardupilot/mavlink_msg_digicam_configure.h \
    mavlink/ardupilot/mavlink_msg_digicam_control.h \
    mavlink/ardupilot/mavlink_msg_ekf_status_report.h \
    mavlink/ardupilot/mavlink_msg_fence_fetch_point.h \
    mavlink/ardupilot/mavlink_msg_fence_point.h \
    mavlink/ardupilot/mavlink_msg_fence_status.h \
    mavlink/ardupilot/mavlink_msg_gimbal_control.h \
    mavlink/ardupilot/mavlink_msg_gimbal_report.h \
    mavlink/ardupilot/mavlink_msg_gimbal_torque_cmd_report.h \
    mavlink/ardupilot/mavlink_msg_gopro_get_request.h \
    mavlink/ardupilot/mavlink_msg_gopro_get_response.h \
    mavlink/ardupilot/mavlink_msg_gopro_heartbeat.h \
    mavlink/ardupilot/mavlink_msg_gopro_set_request.h \
    mavlink/ardupilot/mavlink_msg_gopro_set_response.h \
    mavlink/ardupilot/mavlink_msg_hwstatus.h \
    mavlink/ardupilot/mavlink_msg_led_control.h \
    mavlink/ardupilot/mavlink_msg_limits_status.h \
    mavlink/ardupilot/mavlink_msg_mag_cal_progress.h \
    mavlink/ardupilot/mavlink_msg_mag_cal_report.h \
    mavlink/ardupilot/mavlink_msg_meminfo.h \
    mavlink/ardupilot/mavlink_msg_mount_configure.h \
    mavlink/ardupilot/mavlink_msg_mount_control.h \
    mavlink/ardupilot/mavlink_msg_mount_status.h \
    mavlink/ardupilot/mavlink_msg_pid_tuning.h \
    mavlink/ardupilot/mavlink_msg_radio.h \
    mavlink/ardupilot/mavlink_msg_rally_fetch_point.h \
    mavlink/ardupilot/mavlink_msg_rally_point.h \
    mavlink/ardupilot/mavlink_msg_rangefinder.h \
    mavlink/ardupilot/mavlink_msg_remote_log_block_status.h \
    mavlink/ardupilot/mavlink_msg_remote_log_data_block.h \
    mavlink/ardupilot/mavlink_msg_rpm.h \
    mavlink/ardupilot/mavlink_msg_sensor_offsets.h \
    mavlink/ardupilot/mavlink_msg_set_mag_offsets.h \
    mavlink/ardupilot/mavlink_msg_simstate.h \
    mavlink/ardupilot/mavlink_msg_wind.h \
    mavlink/ardupilot/testsuite.h \
    mavlink/ardupilot/version.h \
    serial_link.h \
    abstract_link.h \
    gcs_communicator_factory.h \
    abstract_communicator_factory.h \
    mavlink_v1/ardupilotmega/ardupilotmega.h \
    mavlink_v1/ardupilotmega/mavlink.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ahrs.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ahrs2.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ahrs3.h \
    mavlink_v1/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ap_adc.h \
    mavlink_v1/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    mavlink_v1/ardupilotmega/mavlink_msg_battery2.h \
    mavlink_v1/ardupilotmega/mavlink_msg_camera_feedback.h \
    mavlink_v1/ardupilotmega/mavlink_msg_camera_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_compassmot_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_data16.h \
    mavlink_v1/ardupilotmega/mavlink_msg_data32.h \
    mavlink_v1/ardupilotmega/mavlink_msg_data64.h \
    mavlink_v1/ardupilotmega/mavlink_msg_data96.h \
    mavlink_v1/ardupilotmega/mavlink_msg_digicam_configure.h \
    mavlink_v1/ardupilotmega/mavlink_msg_digicam_control.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ekf_status_report.h \
    mavlink_v1/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    mavlink_v1/ardupilotmega/mavlink_msg_fence_point.h \
    mavlink_v1/ardupilotmega/mavlink_msg_fence_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gimbal_control.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gimbal_report.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_get_request.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_get_response.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_set_request.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_set_response.h \
    mavlink_v1/ardupilotmega/mavlink_msg_hwstatus.h \
    mavlink_v1/ardupilotmega/mavlink_msg_led_control.h \
    mavlink_v1/ardupilotmega/mavlink_msg_limits_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mag_cal_report.h \
    mavlink_v1/ardupilotmega/mavlink_msg_meminfo.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mount_configure.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mount_control.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mount_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_pid_tuning.h \
    mavlink_v1/ardupilotmega/mavlink_msg_radio.h \
    mavlink_v1/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    mavlink_v1/ardupilotmega/mavlink_msg_rally_point.h \
    mavlink_v1/ardupilotmega/mavlink_msg_rangefinder.h \
    mavlink_v1/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    mavlink_v1/ardupilotmega/mavlink_msg_rpm.h \
    mavlink_v1/ardupilotmega/mavlink_msg_sensor_offsets.h \
    mavlink_v1/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    mavlink_v1/ardupilotmega/mavlink_msg_simstate.h \
    mavlink_v1/ardupilotmega/mavlink_msg_wind.h \
    mavlink_v1/ardupilotmega/testsuite.h \
    mavlink_v1/ardupilotmega/version.h \
    mavlink_v1/ASLUAV/ASLUAV.h \
    mavlink_v1/ASLUAV/mavlink.h \
    mavlink_v1/ASLUAV/mavlink_msg_asl_obctrl.h \
    mavlink_v1/ASLUAV/mavlink_msg_aslctrl_data.h \
    mavlink_v1/ASLUAV/mavlink_msg_aslctrl_debug.h \
    mavlink_v1/ASLUAV/mavlink_msg_asluav_status.h \
    mavlink_v1/ASLUAV/mavlink_msg_ekf_ext.h \
    mavlink_v1/ASLUAV/mavlink_msg_fw_soaring_data.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_atmos.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_batmon.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_mppt.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_power.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_power_board.h \
    mavlink_v1/ASLUAV/mavlink_msg_sensorpod_status.h \
    mavlink_v1/ASLUAV/testsuite.h \
    mavlink_v1/ASLUAV/version.h \
    mavlink_v1/autoquad/autoquad.h \
    mavlink_v1/autoquad/mavlink.h \
    mavlink_v1/autoquad/mavlink_msg_aq_esc_telemetry.h \
    mavlink_v1/autoquad/mavlink_msg_aq_telemetry_f.h \
    mavlink_v1/autoquad/testsuite.h \
    mavlink_v1/autoquad/version.h \
    mavlink_v1/common/common.h \
    mavlink_v1/common/mavlink.h \
    mavlink_v1/common/mavlink_msg_actuator_control_target.h \
    mavlink_v1/common/mavlink_msg_adsb_vehicle.h \
    mavlink_v1/common/mavlink_msg_altitude.h \
    mavlink_v1/common/mavlink_msg_att_pos_mocap.h \
    mavlink_v1/common/mavlink_msg_attitude.h \
    mavlink_v1/common/mavlink_msg_attitude_quaternion.h \
    mavlink_v1/common/mavlink_msg_attitude_quaternion_cov.h \
    mavlink_v1/common/mavlink_msg_attitude_target.h \
    mavlink_v1/common/mavlink_msg_auth_key.h \
    mavlink_v1/common/mavlink_msg_autopilot_version.h \
    mavlink_v1/common/mavlink_msg_battery_status.h \
    mavlink_v1/common/mavlink_msg_camera_trigger.h \
    mavlink_v1/common/mavlink_msg_change_operator_control.h \
    mavlink_v1/common/mavlink_msg_change_operator_control_ack.h \
    mavlink_v1/common/mavlink_msg_collision.h \
    mavlink_v1/common/mavlink_msg_command_ack.h \
    mavlink_v1/common/mavlink_msg_command_int.h \
    mavlink_v1/common/mavlink_msg_command_long.h \
    mavlink_v1/common/mavlink_msg_control_system_state.h \
    mavlink_v1/common/mavlink_msg_data_stream.h \
    mavlink_v1/common/mavlink_msg_data_transmission_handshake.h \
    mavlink_v1/common/mavlink_msg_debug.h \
    mavlink_v1/common/mavlink_msg_debug_vect.h \
    mavlink_v1/common/mavlink_msg_distance_sensor.h \
    mavlink_v1/common/mavlink_msg_encapsulated_data.h \
    mavlink_v1/common/mavlink_msg_estimator_status.h \
    mavlink_v1/common/mavlink_msg_extended_sys_state.h \
    mavlink_v1/common/mavlink_msg_file_transfer_protocol.h \
    mavlink_v1/common/mavlink_msg_follow_target.h \
    mavlink_v1/common/mavlink_msg_global_position_int.h \
    mavlink_v1/common/mavlink_msg_global_position_int_cov.h \
    mavlink_v1/common/mavlink_msg_global_vision_position_estimate.h \
    mavlink_v1/common/mavlink_msg_gps2_raw.h \
    mavlink_v1/common/mavlink_msg_gps2_rtk.h \
    mavlink_v1/common/mavlink_msg_gps_global_origin.h \
    mavlink_v1/common/mavlink_msg_gps_inject_data.h \
    mavlink_v1/common/mavlink_msg_gps_input.h \
    mavlink_v1/common/mavlink_msg_gps_raw_int.h \
    mavlink_v1/common/mavlink_msg_gps_rtcm_data.h \
    mavlink_v1/common/mavlink_msg_gps_rtk.h \
    mavlink_v1/common/mavlink_msg_gps_status.h \
    mavlink_v1/common/mavlink_msg_heartbeat.h \
    mavlink_v1/common/mavlink_msg_highres_imu.h \
    mavlink_v1/common/mavlink_msg_hil_actuator_controls.h \
    mavlink_v1/common/mavlink_msg_hil_controls.h \
    mavlink_v1/common/mavlink_msg_hil_gps.h \
    mavlink_v1/common/mavlink_msg_hil_optical_flow.h \
    mavlink_v1/common/mavlink_msg_hil_rc_inputs_raw.h \
    mavlink_v1/common/mavlink_msg_hil_sensor.h \
    mavlink_v1/common/mavlink_msg_hil_state.h \
    mavlink_v1/common/mavlink_msg_hil_state_quaternion.h \
    mavlink_v1/common/mavlink_msg_home_position.h \
    mavlink_v1/common/mavlink_msg_landing_target.h \
    mavlink_v1/common/mavlink_msg_local_position_ned.h \
    mavlink_v1/common/mavlink_msg_local_position_ned_cov.h \
    mavlink_v1/common/mavlink_msg_local_position_ned_system_global_offset.h \
    mavlink_v1/common/mavlink_msg_log_data.h \
    mavlink_v1/common/mavlink_msg_log_entry.h \
    mavlink_v1/common/mavlink_msg_log_erase.h \
    mavlink_v1/common/mavlink_msg_log_request_data.h \
    mavlink_v1/common/mavlink_msg_log_request_end.h \
    mavlink_v1/common/mavlink_msg_log_request_list.h \
    mavlink_v1/common/mavlink_msg_manual_control.h \
    mavlink_v1/common/mavlink_msg_manual_setpoint.h \
    mavlink_v1/common/mavlink_msg_memory_vect.h \
    mavlink_v1/common/mavlink_msg_message_interval.h \
    mavlink_v1/common/mavlink_msg_mission_ack.h \
    mavlink_v1/common/mavlink_msg_mission_clear_all.h \
    mavlink_v1/common/mavlink_msg_mission_count.h \
    mavlink_v1/common/mavlink_msg_mission_current.h \
    mavlink_v1/common/mavlink_msg_mission_item.h \
    mavlink_v1/common/mavlink_msg_mission_item_int.h \
    mavlink_v1/common/mavlink_msg_mission_item_reached.h \
    mavlink_v1/common/mavlink_msg_mission_request.h \
    mavlink_v1/common/mavlink_msg_mission_request_int.h \
    mavlink_v1/common/mavlink_msg_mission_request_list.h \
    mavlink_v1/common/mavlink_msg_mission_request_partial_list.h \
    mavlink_v1/common/mavlink_msg_mission_set_current.h \
    mavlink_v1/common/mavlink_msg_mission_write_partial_list.h \
    mavlink_v1/common/mavlink_msg_named_value_float.h \
    mavlink_v1/common/mavlink_msg_named_value_int.h \
    mavlink_v1/common/mavlink_msg_nav_controller_output.h \
    mavlink_v1/common/mavlink_msg_optical_flow.h \
    mavlink_v1/common/mavlink_msg_optical_flow_rad.h \
    mavlink_v1/common/mavlink_msg_param_map_rc.h \
    mavlink_v1/common/mavlink_msg_param_request_list.h \
    mavlink_v1/common/mavlink_msg_param_request_read.h \
    mavlink_v1/common/mavlink_msg_param_set.h \
    mavlink_v1/common/mavlink_msg_param_value.h \
    mavlink_v1/common/mavlink_msg_ping.h \
    mavlink_v1/common/mavlink_msg_position_target_global_int.h \
    mavlink_v1/common/mavlink_msg_position_target_local_ned.h \
    mavlink_v1/common/mavlink_msg_power_status.h \
    mavlink_v1/common/mavlink_msg_radio_status.h \
    mavlink_v1/common/mavlink_msg_raw_imu.h \
    mavlink_v1/common/mavlink_msg_raw_pressure.h \
    mavlink_v1/common/mavlink_msg_rc_channels.h \
    mavlink_v1/common/mavlink_msg_rc_channels_override.h \
    mavlink_v1/common/mavlink_msg_rc_channels_raw.h \
    mavlink_v1/common/mavlink_msg_rc_channels_scaled.h \
    mavlink_v1/common/mavlink_msg_request_data_stream.h \
    mavlink_v1/common/mavlink_msg_resource_request.h \
    mavlink_v1/common/mavlink_msg_safety_allowed_area.h \
    mavlink_v1/common/mavlink_msg_safety_set_allowed_area.h \
    mavlink_v1/common/mavlink_msg_scaled_imu.h \
    mavlink_v1/common/mavlink_msg_scaled_imu2.h \
    mavlink_v1/common/mavlink_msg_scaled_imu3.h \
    mavlink_v1/common/mavlink_msg_scaled_pressure.h \
    mavlink_v1/common/mavlink_msg_scaled_pressure2.h \
    mavlink_v1/common/mavlink_msg_scaled_pressure3.h \
    mavlink_v1/common/mavlink_msg_serial_control.h \
    mavlink_v1/common/mavlink_msg_servo_output_raw.h \
    mavlink_v1/common/mavlink_msg_set_actuator_control_target.h \
    mavlink_v1/common/mavlink_msg_set_attitude_target.h \
    mavlink_v1/common/mavlink_msg_set_gps_global_origin.h \
    mavlink_v1/common/mavlink_msg_set_home_position.h \
    mavlink_v1/common/mavlink_msg_set_mode.h \
    mavlink_v1/common/mavlink_msg_set_position_target_global_int.h \
    mavlink_v1/common/mavlink_msg_set_position_target_local_ned.h \
    mavlink_v1/common/mavlink_msg_sim_state.h \
    mavlink_v1/common/mavlink_msg_statustext.h \
    mavlink_v1/common/mavlink_msg_sys_status.h \
    mavlink_v1/common/mavlink_msg_system_time.h \
    mavlink_v1/common/mavlink_msg_terrain_check.h \
    mavlink_v1/common/mavlink_msg_terrain_data.h \
    mavlink_v1/common/mavlink_msg_terrain_report.h \
    mavlink_v1/common/mavlink_msg_terrain_request.h \
    mavlink_v1/common/mavlink_msg_timesync.h \
    mavlink_v1/common/mavlink_msg_v2_extension.h \
    mavlink_v1/common/mavlink_msg_vfr_hud.h \
    mavlink_v1/common/mavlink_msg_vibration.h \
    mavlink_v1/common/mavlink_msg_vicon_position_estimate.h \
    mavlink_v1/common/mavlink_msg_vision_position_estimate.h \
    mavlink_v1/common/mavlink_msg_vision_speed_estimate.h \
    mavlink_v1/common/mavlink_msg_wind_cov.h \
    mavlink_v1/common/testsuite.h \
    mavlink_v1/common/version.h \
    mavlink_v1/matrixpilot/matrixpilot.h \
    mavlink_v1/matrixpilot/mavlink.h \
    mavlink_v1/matrixpilot/mavlink_msg_airspeeds.h \
    mavlink_v1/matrixpilot/mavlink_msg_altitudes.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_command.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_directory.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_set.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    mavlink_v1/matrixpilot/testsuite.h \
    mavlink_v1/matrixpilot/version.h \
    mavlink_v1/minimal/mavlink.h \
    mavlink_v1/minimal/mavlink_msg_heartbeat.h \
    mavlink_v1/minimal/minimal.h \
    mavlink_v1/minimal/testsuite.h \
    mavlink_v1/minimal/version.h \
    mavlink_v1/slugs/mavlink.h \
    mavlink_v1/slugs/mavlink_msg_boot.h \
    mavlink_v1/slugs/mavlink_msg_control_surface.h \
    mavlink_v1/slugs/mavlink_msg_cpu_load.h \
    mavlink_v1/slugs/mavlink_msg_ctrl_srfc_pt.h \
    mavlink_v1/slugs/mavlink_msg_data_log.h \
    mavlink_v1/slugs/mavlink_msg_diagnostic.h \
    mavlink_v1/slugs/mavlink_msg_gps_date_time.h \
    mavlink_v1/slugs/mavlink_msg_isr_location.h \
    mavlink_v1/slugs/mavlink_msg_mid_lvl_cmds.h \
    mavlink_v1/slugs/mavlink_msg_novatel_diag.h \
    mavlink_v1/slugs/mavlink_msg_ptz_status.h \
    mavlink_v1/slugs/mavlink_msg_sensor_bias.h \
    mavlink_v1/slugs/mavlink_msg_sensor_diag.h \
    mavlink_v1/slugs/mavlink_msg_slugs_camera_order.h \
    mavlink_v1/slugs/mavlink_msg_slugs_configuration_camera.h \
    mavlink_v1/slugs/mavlink_msg_slugs_mobile_location.h \
    mavlink_v1/slugs/mavlink_msg_slugs_navigation.h \
    mavlink_v1/slugs/mavlink_msg_status_gps.h \
    mavlink_v1/slugs/mavlink_msg_uav_status.h \
    mavlink_v1/slugs/mavlink_msg_volt_sensor.h \
    mavlink_v1/slugs/slugs.h \
    mavlink_v1/slugs/testsuite.h \
    mavlink_v1/slugs/version.h \
    mavlink_v1/test/mavlink.h \
    mavlink_v1/test/mavlink_msg_test_types.h \
    mavlink_v1/test/test.h \
    mavlink_v1/test/testsuite.h \
    mavlink_v1/test/version.h \
    mavlink_v1/uAvionix/mavlink.h \
    mavlink_v1/uAvionix/testsuite.h \
    mavlink_v1/uAvionix/uAvionix.h \
    mavlink_v1/uAvionix/version.h \
    mavlink_v1/checksum.h \
    mavlink_v1/mavlink_conversions.h \
    mavlink_v1/mavlink_helpers.h \
    mavlink_v1/mavlink_types.h \
    mavlink_v1/protocol.h \
    mavlink_v1/ardupilotmega/ardupilotmega.h \
    mavlink_v1/ardupilotmega/mavlink.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ahrs.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ahrs2.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ahrs3.h \
    mavlink_v1/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ap_adc.h \
    mavlink_v1/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    mavlink_v1/ardupilotmega/mavlink_msg_battery2.h \
    mavlink_v1/ardupilotmega/mavlink_msg_camera_feedback.h \
    mavlink_v1/ardupilotmega/mavlink_msg_camera_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_compassmot_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_data16.h \
    mavlink_v1/ardupilotmega/mavlink_msg_data32.h \
    mavlink_v1/ardupilotmega/mavlink_msg_data64.h \
    mavlink_v1/ardupilotmega/mavlink_msg_data96.h \
    mavlink_v1/ardupilotmega/mavlink_msg_digicam_configure.h \
    mavlink_v1/ardupilotmega/mavlink_msg_digicam_control.h \
    mavlink_v1/ardupilotmega/mavlink_msg_ekf_status_report.h \
    mavlink_v1/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    mavlink_v1/ardupilotmega/mavlink_msg_fence_point.h \
    mavlink_v1/ardupilotmega/mavlink_msg_fence_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gimbal_control.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gimbal_report.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_get_request.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_get_response.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_set_request.h \
    mavlink_v1/ardupilotmega/mavlink_msg_gopro_set_response.h \
    mavlink_v1/ardupilotmega/mavlink_msg_hwstatus.h \
    mavlink_v1/ardupilotmega/mavlink_msg_led_control.h \
    mavlink_v1/ardupilotmega/mavlink_msg_limits_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mag_cal_report.h \
    mavlink_v1/ardupilotmega/mavlink_msg_meminfo.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mount_configure.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mount_control.h \
    mavlink_v1/ardupilotmega/mavlink_msg_mount_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_pid_tuning.h \
    mavlink_v1/ardupilotmega/mavlink_msg_radio.h \
    mavlink_v1/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    mavlink_v1/ardupilotmega/mavlink_msg_rally_point.h \
    mavlink_v1/ardupilotmega/mavlink_msg_rangefinder.h \
    mavlink_v1/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    mavlink_v1/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    mavlink_v1/ardupilotmega/mavlink_msg_rpm.h \
    mavlink_v1/ardupilotmega/mavlink_msg_sensor_offsets.h \
    mavlink_v1/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    mavlink_v1/ardupilotmega/mavlink_msg_simstate.h \
    mavlink_v1/ardupilotmega/mavlink_msg_wind.h \
    mavlink_v1/ardupilotmega/testsuite.h \
    mavlink_v1/ardupilotmega/version.h \
    mavlink_v1/ASLUAV/ASLUAV.h \
    mavlink_v1/ASLUAV/mavlink.h \
    mavlink_v1/ASLUAV/mavlink_msg_asl_obctrl.h \
    mavlink_v1/ASLUAV/mavlink_msg_aslctrl_data.h \
    mavlink_v1/ASLUAV/mavlink_msg_aslctrl_debug.h \
    mavlink_v1/ASLUAV/mavlink_msg_asluav_status.h \
    mavlink_v1/ASLUAV/mavlink_msg_ekf_ext.h \
    mavlink_v1/ASLUAV/mavlink_msg_fw_soaring_data.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_atmos.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_batmon.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_mppt.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_power.h \
    mavlink_v1/ASLUAV/mavlink_msg_sens_power_board.h \
    mavlink_v1/ASLUAV/mavlink_msg_sensorpod_status.h \
    mavlink_v1/ASLUAV/testsuite.h \
    mavlink_v1/ASLUAV/version.h \
    mavlink_v1/autoquad/autoquad.h \
    mavlink_v1/autoquad/mavlink.h \
    mavlink_v1/autoquad/mavlink_msg_aq_esc_telemetry.h \
    mavlink_v1/autoquad/mavlink_msg_aq_telemetry_f.h \
    mavlink_v1/autoquad/testsuite.h \
    mavlink_v1/autoquad/version.h \
    mavlink_v1/common/common.h \
    mavlink_v1/common/mavlink.h \
    mavlink_v1/common/mavlink_msg_actuator_control_target.h \
    mavlink_v1/common/mavlink_msg_adsb_vehicle.h \
    mavlink_v1/common/mavlink_msg_altitude.h \
    mavlink_v1/common/mavlink_msg_att_pos_mocap.h \
    mavlink_v1/common/mavlink_msg_attitude.h \
    mavlink_v1/common/mavlink_msg_attitude_quaternion.h \
    mavlink_v1/common/mavlink_msg_attitude_quaternion_cov.h \
    mavlink_v1/common/mavlink_msg_attitude_target.h \
    mavlink_v1/common/mavlink_msg_auth_key.h \
    mavlink_v1/common/mavlink_msg_autopilot_version.h \
    mavlink_v1/common/mavlink_msg_battery_status.h \
    mavlink_v1/common/mavlink_msg_camera_trigger.h \
    mavlink_v1/common/mavlink_msg_change_operator_control.h \
    mavlink_v1/common/mavlink_msg_change_operator_control_ack.h \
    mavlink_v1/common/mavlink_msg_collision.h \
    mavlink_v1/common/mavlink_msg_command_ack.h \
    mavlink_v1/common/mavlink_msg_command_int.h \
    mavlink_v1/common/mavlink_msg_command_long.h \
    mavlink_v1/common/mavlink_msg_control_system_state.h \
    mavlink_v1/common/mavlink_msg_data_stream.h \
    mavlink_v1/common/mavlink_msg_data_transmission_handshake.h \
    mavlink_v1/common/mavlink_msg_debug.h \
    mavlink_v1/common/mavlink_msg_debug_vect.h \
    mavlink_v1/common/mavlink_msg_distance_sensor.h \
    mavlink_v1/common/mavlink_msg_encapsulated_data.h \
    mavlink_v1/common/mavlink_msg_estimator_status.h \
    mavlink_v1/common/mavlink_msg_extended_sys_state.h \
    mavlink_v1/common/mavlink_msg_file_transfer_protocol.h \
    mavlink_v1/common/mavlink_msg_follow_target.h \
    mavlink_v1/common/mavlink_msg_global_position_int.h \
    mavlink_v1/common/mavlink_msg_global_position_int_cov.h \
    mavlink_v1/common/mavlink_msg_global_vision_position_estimate.h \
    mavlink_v1/common/mavlink_msg_gps2_raw.h \
    mavlink_v1/common/mavlink_msg_gps2_rtk.h \
    mavlink_v1/common/mavlink_msg_gps_global_origin.h \
    mavlink_v1/common/mavlink_msg_gps_inject_data.h \
    mavlink_v1/common/mavlink_msg_gps_input.h \
    mavlink_v1/common/mavlink_msg_gps_raw_int.h \
    mavlink_v1/common/mavlink_msg_gps_rtcm_data.h \
    mavlink_v1/common/mavlink_msg_gps_rtk.h \
    mavlink_v1/common/mavlink_msg_gps_status.h \
    mavlink_v1/common/mavlink_msg_heartbeat.h \
    mavlink_v1/common/mavlink_msg_highres_imu.h \
    mavlink_v1/common/mavlink_msg_hil_actuator_controls.h \
    mavlink_v1/common/mavlink_msg_hil_controls.h \
    mavlink_v1/common/mavlink_msg_hil_gps.h \
    mavlink_v1/common/mavlink_msg_hil_optical_flow.h \
    mavlink_v1/common/mavlink_msg_hil_rc_inputs_raw.h \
    mavlink_v1/common/mavlink_msg_hil_sensor.h \
    mavlink_v1/common/mavlink_msg_hil_state.h \
    mavlink_v1/common/mavlink_msg_hil_state_quaternion.h \
    mavlink_v1/common/mavlink_msg_home_position.h \
    mavlink_v1/common/mavlink_msg_landing_target.h \
    mavlink_v1/common/mavlink_msg_local_position_ned.h \
    mavlink_v1/common/mavlink_msg_local_position_ned_cov.h \
    mavlink_v1/common/mavlink_msg_local_position_ned_system_global_offset.h \
    mavlink_v1/common/mavlink_msg_log_data.h \
    mavlink_v1/common/mavlink_msg_log_entry.h \
    mavlink_v1/common/mavlink_msg_log_erase.h \
    mavlink_v1/common/mavlink_msg_log_request_data.h \
    mavlink_v1/common/mavlink_msg_log_request_end.h \
    mavlink_v1/common/mavlink_msg_log_request_list.h \
    mavlink_v1/common/mavlink_msg_manual_control.h \
    mavlink_v1/common/mavlink_msg_manual_setpoint.h \
    mavlink_v1/common/mavlink_msg_memory_vect.h \
    mavlink_v1/common/mavlink_msg_message_interval.h \
    mavlink_v1/common/mavlink_msg_mission_ack.h \
    mavlink_v1/common/mavlink_msg_mission_clear_all.h \
    mavlink_v1/common/mavlink_msg_mission_count.h \
    mavlink_v1/common/mavlink_msg_mission_current.h \
    mavlink_v1/common/mavlink_msg_mission_item.h \
    mavlink_v1/common/mavlink_msg_mission_item_int.h \
    mavlink_v1/common/mavlink_msg_mission_item_reached.h \
    mavlink_v1/common/mavlink_msg_mission_request.h \
    mavlink_v1/common/mavlink_msg_mission_request_int.h \
    mavlink_v1/common/mavlink_msg_mission_request_list.h \
    mavlink_v1/common/mavlink_msg_mission_request_partial_list.h \
    mavlink_v1/common/mavlink_msg_mission_set_current.h \
    mavlink_v1/common/mavlink_msg_mission_write_partial_list.h \
    mavlink_v1/common/mavlink_msg_named_value_float.h \
    mavlink_v1/common/mavlink_msg_named_value_int.h \
    mavlink_v1/common/mavlink_msg_nav_controller_output.h \
    mavlink_v1/common/mavlink_msg_optical_flow.h \
    mavlink_v1/common/mavlink_msg_optical_flow_rad.h \
    mavlink_v1/common/mavlink_msg_param_map_rc.h \
    mavlink_v1/common/mavlink_msg_param_request_list.h \
    mavlink_v1/common/mavlink_msg_param_request_read.h \
    mavlink_v1/common/mavlink_msg_param_set.h \
    mavlink_v1/common/mavlink_msg_param_value.h \
    mavlink_v1/common/mavlink_msg_ping.h \
    mavlink_v1/common/mavlink_msg_position_target_global_int.h \
    mavlink_v1/common/mavlink_msg_position_target_local_ned.h \
    mavlink_v1/common/mavlink_msg_power_status.h \
    mavlink_v1/common/mavlink_msg_radio_status.h \
    mavlink_v1/common/mavlink_msg_raw_imu.h \
    mavlink_v1/common/mavlink_msg_raw_pressure.h \
    mavlink_v1/common/mavlink_msg_rc_channels.h \
    mavlink_v1/common/mavlink_msg_rc_channels_override.h \
    mavlink_v1/common/mavlink_msg_rc_channels_raw.h \
    mavlink_v1/common/mavlink_msg_rc_channels_scaled.h \
    mavlink_v1/common/mavlink_msg_request_data_stream.h \
    mavlink_v1/common/mavlink_msg_resource_request.h \
    mavlink_v1/common/mavlink_msg_safety_allowed_area.h \
    mavlink_v1/common/mavlink_msg_safety_set_allowed_area.h \
    mavlink_v1/common/mavlink_msg_scaled_imu.h \
    mavlink_v1/common/mavlink_msg_scaled_imu2.h \
    mavlink_v1/common/mavlink_msg_scaled_imu3.h \
    mavlink_v1/common/mavlink_msg_scaled_pressure.h \
    mavlink_v1/common/mavlink_msg_scaled_pressure2.h \
    mavlink_v1/common/mavlink_msg_scaled_pressure3.h \
    mavlink_v1/common/mavlink_msg_serial_control.h \
    mavlink_v1/common/mavlink_msg_servo_output_raw.h \
    mavlink_v1/common/mavlink_msg_set_actuator_control_target.h \
    mavlink_v1/common/mavlink_msg_set_attitude_target.h \
    mavlink_v1/common/mavlink_msg_set_gps_global_origin.h \
    mavlink_v1/common/mavlink_msg_set_home_position.h \
    mavlink_v1/common/mavlink_msg_set_mode.h \
    mavlink_v1/common/mavlink_msg_set_position_target_global_int.h \
    mavlink_v1/common/mavlink_msg_set_position_target_local_ned.h \
    mavlink_v1/common/mavlink_msg_sim_state.h \
    mavlink_v1/common/mavlink_msg_statustext.h \
    mavlink_v1/common/mavlink_msg_sys_status.h \
    mavlink_v1/common/mavlink_msg_system_time.h \
    mavlink_v1/common/mavlink_msg_terrain_check.h \
    mavlink_v1/common/mavlink_msg_terrain_data.h \
    mavlink_v1/common/mavlink_msg_terrain_report.h \
    mavlink_v1/common/mavlink_msg_terrain_request.h \
    mavlink_v1/common/mavlink_msg_timesync.h \
    mavlink_v1/common/mavlink_msg_v2_extension.h \
    mavlink_v1/common/mavlink_msg_vfr_hud.h \
    mavlink_v1/common/mavlink_msg_vibration.h \
    mavlink_v1/common/mavlink_msg_vicon_position_estimate.h \
    mavlink_v1/common/mavlink_msg_vision_position_estimate.h \
    mavlink_v1/common/mavlink_msg_vision_speed_estimate.h \
    mavlink_v1/common/mavlink_msg_wind_cov.h \
    mavlink_v1/common/testsuite.h \
    mavlink_v1/common/version.h \
    mavlink_v1/matrixpilot/matrixpilot.h \
    mavlink_v1/matrixpilot/mavlink.h \
    mavlink_v1/matrixpilot/mavlink_msg_airspeeds.h \
    mavlink_v1/matrixpilot/mavlink_msg_altitudes.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_command.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_directory.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    mavlink_v1/matrixpilot/mavlink_msg_flexifunction_set.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    mavlink_v1/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    mavlink_v1/matrixpilot/testsuite.h \
    mavlink_v1/matrixpilot/version.h \
    mavlink_v1/minimal/mavlink.h \
    mavlink_v1/minimal/mavlink_msg_heartbeat.h \
    mavlink_v1/minimal/minimal.h \
    mavlink_v1/minimal/testsuite.h \
    mavlink_v1/minimal/version.h \
    mavlink_v1/slugs/mavlink.h \
    mavlink_v1/slugs/mavlink_msg_boot.h \
    mavlink_v1/slugs/mavlink_msg_control_surface.h \
    mavlink_v1/slugs/mavlink_msg_cpu_load.h \
    mavlink_v1/slugs/mavlink_msg_ctrl_srfc_pt.h \
    mavlink_v1/slugs/mavlink_msg_data_log.h \
    mavlink_v1/slugs/mavlink_msg_diagnostic.h \
    mavlink_v1/slugs/mavlink_msg_gps_date_time.h \
    mavlink_v1/slugs/mavlink_msg_isr_location.h \
    mavlink_v1/slugs/mavlink_msg_mid_lvl_cmds.h \
    mavlink_v1/slugs/mavlink_msg_novatel_diag.h \
    mavlink_v1/slugs/mavlink_msg_ptz_status.h \
    mavlink_v1/slugs/mavlink_msg_sensor_bias.h \
    mavlink_v1/slugs/mavlink_msg_sensor_diag.h \
    mavlink_v1/slugs/mavlink_msg_slugs_camera_order.h \
    mavlink_v1/slugs/mavlink_msg_slugs_configuration_camera.h \
    mavlink_v1/slugs/mavlink_msg_slugs_mobile_location.h \
    mavlink_v1/slugs/mavlink_msg_slugs_navigation.h \
    mavlink_v1/slugs/mavlink_msg_status_gps.h \
    mavlink_v1/slugs/mavlink_msg_uav_status.h \
    mavlink_v1/slugs/mavlink_msg_volt_sensor.h \
    mavlink_v1/slugs/slugs.h \
    mavlink_v1/slugs/testsuite.h \
    mavlink_v1/slugs/version.h \
    mavlink_v1/test/mavlink.h \
    mavlink_v1/test/mavlink_msg_test_types.h \
    mavlink_v1/test/test.h \
    mavlink_v1/test/testsuite.h \
    mavlink_v1/test/version.h \
    mavlink_v1/uAvionix/mavlink.h \
    mavlink_v1/uAvionix/testsuite.h \
    mavlink_v1/uAvionix/uAvionix.h \
    mavlink_v1/uAvionix/version.h \
    mavlink_v1/checksum.h \
    mavlink_v1/mavlink_conversions.h \
    mavlink_v1/mavlink_helpers.h \
    mavlink_v1/mavlink_types.h \
    mavlink_v1/protocol.h \
    mavlink_communicator.h \
    hearthbeat_handler.h \
    abstract_handler.h \
    attitude_handler.h \
    models/missionmodel.h

DISTFILES += \
    database/DataBase.db \
    .gitignore \
    jsonpath.js \
    AddTrackForm.ui.qml \
    AddTracksForm.ui.qml \
    CalibratePopupForm.ui.qml \
    ChangeColorTrackPopupForm.ui.qml \
    DroneV3Form.ui.qml \
    ImagePageForm.ui.qml \
    InstrumentsForm.ui.qml \
    InstrumentsImageForm.ui.qml \
    LeftTabMenuForm.ui.qml \
    LoginPageForm.ui.qml \
    MainMenuForm.ui.qml \
    MainPageForm.ui.qml \
    MapWindowForm.ui.qml \
    OpenTracksForm.ui.qml \
    Page1Form.ui.qml \
    PopupPointsForm.ui.qml \
    AddTrack.qml \
    AddTracks.qml \
    BusyIndicator.qml \
    CalibratePopup.qml \
    ChangeColorTrackPopup.qml \
    ChooseTrackDirDialog.qml \
    CustomPlugin.qml \
    DroneV3.qml \
    EsriPlugin.qml \
    ExportFileDialog.qml \
    HerePlugin.qml \
    ImageGrid.qml \
    ImagePage.qml \
    ImagePageModel.qml \
    ImagePageSlider.qml \
    Instruments.qml \
    InstrumentsImage.qml \
    JSONListModel.qml \
    LeftTabMenu.qml \
    LoginPage.qml \
    main.qml \
    MainMenu.qml \
    MainPage.qml \
    MapboxPlugin.qml \
    MapComponent.qml \
    MapTemplate.qml \
    MapWindow.qml \
    OpenTracks.qml \
    OsmPlugin.qml \
    Page1.qml \
    PopupPoints.qml \
    TihoretskPlugin.qml \
    VideoWindows.qml \
    models/TrackPointer.qml \
    TrackPointer.qml \
    ControlForm.ui.qml \
    Control.qml \
    mavlink_v1/message_definitions/ardupilotmega.xml \
    mavlink_v1/message_definitions/ASLUAV.xml \
    mavlink_v1/message_definitions/autoquad.xml \
    mavlink_v1/message_definitions/common.xml \
    mavlink_v1/message_definitions/matrixpilot.xml \
    mavlink_v1/message_definitions/minimal.xml \
    mavlink_v1/message_definitions/paparazzi.xml \
    mavlink_v1/message_definitions/python_array_test.xml \
    mavlink_v1/message_definitions/slugs.xml \
    mavlink_v1/message_definitions/test.xml \
    mavlink_v1/message_definitions/ualberta.xml \
    mavlink_v1/message_definitions/uAvionix.xml \
    mavlink_v1/message_definitions/ardupilotmega.xml \
    mavlink_v1/message_definitions/ASLUAV.xml \
    mavlink_v1/message_definitions/autoquad.xml \
    mavlink_v1/message_definitions/common.xml \
    mavlink_v1/message_definitions/matrixpilot.xml \
    mavlink_v1/message_definitions/minimal.xml \
    mavlink_v1/message_definitions/paparazzi.xml \
    mavlink_v1/message_definitions/python_array_test.xml \
    mavlink_v1/message_definitions/slugs.xml \
    mavlink_v1/message_definitions/test.xml \
    mavlink_v1/message_definitions/ualberta.xml \
    mavlink_v1/message_definitions/uAvionix.xml

win32
{
    #INCLUDEPATH += C:/opencv/build/include
    #LIBS += -LC:/opencv/build/bin -lopencv_core320 \
    #    -lopencv_highgui320 \
    #    -lopencv_imgcodecs320 \
    #    -lopencv_imgproc320 \
    #    -lopencv_features2d320 \
    #    -lopencv_calib3d320
    #LIBS += C:/OSGeo4W/apps/Python27/libs/python27.lib
    #INCLUDEPATH += C:/OSGeo4W/apps/Python27/include
}
unix
{
    INCLUDEPATH += /usr/local/include/opencv2
    LIBS += -L/usr/local/lib
    LIBS += -lopencv_core
    LIBS += -lopencv_imgproc
    LIBS += -lopencv_highgui
    LIBS += -lopencv_imgcodecs
    LIBS += -lopencv_features2d
    LIBS += -lopencv_calib3d
}


#LIBS       += -lVLCQtCore -lVLCQtWidgets -lVLCQtQml
